### ISSUE TITLE
Dutch sentiment analysis not working

### ISSUE THREAD

**Issue by frederatic** [bnosac/pattern.nlp#12]
I got it working, but when I try your examples for pattern_sentiment, the dutch one outputs 0.00 for both polarity and subjectivity. I tried the same example in python 2.7 with pattern 2.6 and it gives the same results, so I assume the problem lies with pattern. Problem is I can't install the latest pattern version with python 2.7, cuz it says it requires >3.5. And this R package can't use 3.5 as it says in your Read.me. How do I fix this so I can get the same output as yours?

**Comment by jwijffels** [comment]
Try a bit more :) on installing pattern in python.  https://www.clips.uantwerpen.be/pattern

**Comment by frederatic** [comment]
Only problem I can see from that page is that I installed both pattern 2.6 and 3.6 using setup.py install since pip install gave errors.
I tried their examples in python 2.7 (pattern 2.6), python 3.6 (pattern 3.6) and your package in R.studio: all gave the same results matching their output.
For your example, it gives 0.00 in both python 2.7 and R, but (-0.2, 0.4) in python 3.6. I have no idea how this can happen, so can you help me out? I have to make sure the sentiment analysis is as accurate as possible once I apply it to a large data set.

**Comment by frederatic** [comment]
Their example: "Een onwijs spannend goed boek!"
Your example: "We waren bijna bij de kooien toen er van boven een hoeragejuich losbrak alsof Rudi Vuller door Koeman in z'n kloten was geschopt."

**Comment by jwijffels** [comment]
I don't understand your problem. It seems to be working? This R package executes py <- findpython::can_find_python_cmd(required_modules = "pattern.db") at startup of the package to connect to pattern. If it finds that one it will use it. What does that command give for your computer.

**Comment by frederatic** [comment]
Yes, it works, but the dutch example in your Read.me outputs different results for me (see above), so that worries me it won't be accurate on other sentences.

**Comment by jwijffels** [comment]
Why don't you just remove either the python2 or python3 pattern module, whichever you don't like.

**Comment by frederatic** [comment]
Tried, did not change any results. It works fine on other sentences, so I think that specific example is just an outlier. Can you try the examples posted above (both in python and R) and send me your output just to make sure?
