### ISSUE TITLE
Installation on R 3.3.2

### ISSUE THREAD

**Issue by ghost** [bnosac/pattern.nlp#2]
Thanks a lot for this package ! I couldn't install it on the latest R version (3.3.2), gives this error:
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'pack'
However installation on R 3.2.3 succeeded.

**Comment by jwijffels** [comment]
The error message comes from devtools, not from the pattern.nlp package.
Can you start a new R session and install as follows. 

```
install.packages('Rcpp')
install.packages('xml2')
install.packages('data.table')
install.packages('digest')
install.packages('findpython')
install.packages('PythonInR')
install.packages('devtools')
devtools::install_github("bnosac/pattern.nlp", args = "--no-multiarch")

```

**Comment by karl08** [comment]
it says...

> library(pattern.nlp)
Error in find_python_cmd(minimum_version = minimum_version, maximum_version = maximum_version,  : 
  Couldn't find a sufficient Python binary. If you haven't installed the Python dependency yet please do so. If you have but it isn't on the system path (as is default on Windows) please add it to path or set options('python_cmd'='/path/to/binary')  or set the PYTHON, PYTHON2, or PYTHON3 environmental variables.   Python must have access to the modules: pattern.db

**Comment by jwijffels** [comment]
Please follow the README for installing the package. If you are stuck installing the package, you can also use the udpipe R package which has basically the same functionalities except sentiment scoring.
