### ISSUE TITLE
I can't install the package

### ISSUE THREAD

**Issue by nguyen0000** [bnosac/pattern.nlp#6]
Hello
 i have installed the Python 2.5.4 and i tried to install the pattern package but it doesn't work. Do you have a tutorial or something easier for me please ?

Thank you

**Comment by jwijffels** [comment]
pip install pattern
Put Python in the PATH and next
devtools::install_github("bnosac/pattern.nlp", args = "--no-multiarch")
As indicated in the INSTALLATION part of the readme

**Comment by nguyen0000** [comment]
thanks for your answer but what is  pip install pattern ? what should i do exactly ? sorry but i'm beginning who want to learn

**Comment by jwijffels** [comment]
pip is python's package manager.
pip install pattern installs the pattern library from PyPi.
It's like you do install.packages("data.table") in R

**Comment by nguyen0000** [comment]
where should i do this instruction ? in the python (command line ) i have seen some tuto , they did it in the cmd
