### ISSUE TITLE
Error in pyExec

### ISSUE THREAD

**Issue by heinbakker** [bnosac/pattern.nlp#7]
After installing I tried to test the code with the example text:

> library(pattern.nlp)
> pattern_sentiment("i really really hate iphones", language = "english")

But then I get the following error:

Error in pyExec(sprintf("senti = %s(%s)", FUN, pyobj)) : 
   Traceback (most recent call last):
     File "<string>", line 1, in <module>
   NameError: name 'sentiment_en' is not defined

What could be wrong and how could I try to fix it?

**Comment by isathish** [comment]
i am also facing same issue

**Comment by jwijffels** [comment]
Closing. Follow the installation instructions in the README.

**Comment by hack-r** [comment]
@jwijffels  This issue is coming up for me as a sub-issue of Issue #9  . I've done everything in the README.
